name: visitors_flow_app
description: control of visitors
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter_localizations:
    sdk: flutter        
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^3.2.2+1
  mobx: ^2.0.0-nullsafety.2
  flutter_mobx: ^2.0.0
  dio: ^4.0.0
  shared_preferences: ^2.0.6
  string_validator: ^0.3.0
  dartz: ^0.10.0-nullsafety.2
  asuka: ^2.0.0-nullsafety.2
  google_fonts:
  hexcolor: ^2.0.4
  font_awesome_flutter: ^9.1.0
  url_launcher: ^5.0.2
  image_picker: ^0.6.0+3
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.3
  mobx_codegen: ^2.0.1+3

flutter:
  uses-material-design: true
  assets:
     - assets/images/